### ISSUE TITLE
Working config with EPShome WT32-ETH01 V1.4

### ISSUE THREAD

**Issue by mati294** [egnor/wt32-eth01#12]
Please add this info how to play with it on ESPhome.
This works for V1.4
Thanks

`
ethernet:
  type: LAN8720
  mdc_pin: GPIO23
  mdio_pin: GPIO18
  clk_mode: GPIO0_IN
  phy_addr: 1
  power_pin: GPIO16

`

**Comment by egnor** [comment]
Should be done! Check to make sure I got it right?
