### ISSUE TITLE
Issue while flashing - any idea?

### ISSUE THREAD

**Issue by yannik2480** [egnor/wt32-eth01#9]
Hello everyone,

I recently acquired two ESP32 devices and am facing significant issues while attempting to flash them. The devices are:

1. ESP32 ETH01 WT32
2. ESP32 WROOM-32

The ESP32 ETH01 does not have a USB-C port, so the data transfer for flashing must be done through the pins. I am using a CP2102 adapter to make the connection. When connected, the TXD and RXD LEDs on both the CP2102 and the ETH01 blink rapidly and repeatedly.

Unfortunately, when I attempt to flash the devices, I consistently encounter the following errors:

Error 1:
```
COM14 failed to connect: Failed to connect to Espressif device: Serial data stream stopped: Possible serial noise or corruption.
```
Error 2:
```
A fatal error occurred: Failed to connect to ESP32: No serial data received.
```

The flashing process always halts after a series of dots following "Connecting......."

Here is the precise output of the flashing process:
```
Sketch uses 279213 bytes (3%) of program storage space. Maximum is 8388608 bytes.
Global variables use 20200 bytes (6%) of dynamic memory, leaving 307480 bytes for local variables. Maximum is 327680 bytes.
esptool.py v4.6
Serial port COM4
Connecting......................................
```

Although the ESP32 receives power, the same error occurs when attempting to flash it.

Does anyone have any ideas on what the issue might be or steps I can take to resolve this problem? I would greatly appreciate any help or tips.

Thank you in advance for your support!

**Comment by egnor** [comment]
I'm not really here for general debugging, butttttt I am a big softie soooooo...

Can you post a diagram of exactly what is wired to what?
